hook:
  placeholderapi: true
  luckperms: true

settings:
  #Store keys in memory. Attention! If you have a large files
  #with keys, this will significantly affect your RAM usage.
  store-keys-in-memory: true
  #Temporarily stores the value of the result for quick return on re-query.
  #If 0 or lower, then no values are stored.
  store-requested-values: 5 #minutes
  #Available language translations for player to choose from.
  #Note: plugin will automatically create file on reload.
  languages:
    - en
    - ru
  #Language that will be set to a player by default.
  default-language: en
  #Choose priority for events for this plugin.
  #This will affect if other plugin can change message.
  #For example: if you have plugin that change messages and
  #this options is set to LOWEST, then that plugin could overwrite these placeholder.
  #
  #Available options: LOWEST, LOW, NORMAL, HIGH, HIGHEST.
  event-priority: LOWEST
  check-placeholder-on:
    rename-item-on-anvil-event: true
    edit-book-event: true

#MySQL. If the connection data is entered incorrectly,
#then the data will be written to the local database.
mysql:
  enabled: false
  updateTime: 30 #minutes
  prefix: 'lngbr_'
  host: ''
  port: ''
  database: ''
  user: ''
  password: ''

debug: false