name: LanguageBridge
author: Astroreen
version: '${version}'
main: me.astroreen.languagebridge.LanguageBridge
api-version: '1.20'
depend:
  - AstroLibs
  - ProtocolLib
softdepend:
  - LuckPerms
  - PlaceholderAPI

commands:
  languagebridgetest:
    description: Command for plugin tests
    aliases:
      - languagebrtest
      - lngbridgetest
      - lngbrtest
      - lngbrtest
      - lnbrtest
      - languagebrt
      - lngbridget
      - lngbrt
      - lngbrt
      - lnbrt
      - test
  languagebridge:
    description: Main command
    permission: languagebridge.command.languagebridge
    aliases:
      - languagebr
      - lngbridge
      - lngbr
      - lngbr
      - lnbr
  language:
    description: Command to choose your language
    permission: languagebridge.command.language
    aliases:
      - lang
      - lng