name: LanguageBridge
author: Astroreen
version: '${version}'
main: me.astroreen.languagebridge.LanguageBridge
api-version: '1.20'
depend:
  - AstroLibs
softdepend:
  - LuckPerms
  - PlaceholderAPI

commands:
  languagebridge:
    description: Main command
    permission: languagebridge.command.languagebridge
    aliases:
      - languagebr
      - lngbridge
      - lngbr
      - lngbr
      - lnbr